name: helloworld
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - name: Hello world action step
        id: hello
        uses: josephdipu/hello-world-javascript-action@v1.1
        with:
          who-to-greet: 'Mona the JosephDipu'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
  goodday:
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: |
          echo Good day!
  bye:
     #runs-on: ubuntu-latest
     runs-on: self-hosted
     steps:
     - name: Run a one-line script
       run: echo Good Bye!
     needs: [hello,goodday]
